import InfiniteExhibition, { type ExhibitionItem } from "../components/InfiniteExhibition";

export const dynamic = "force-static";

const items: ExhibitionItem[] = [
  {eyebrow:"ORIGINS OF ASTRONOMY",title:"The First Sky Maps",period:"c. 1600 BCE",intro:"Long before telescopes, the sky was humanity's clock, calendar and compass.",body:"Mesopotamian observers recorded repeating paths of planets and stars on clay. Their patient observations transformed wonder into one of the earliest systematic sciences.",image:"/exhibit-ancient-stargazers.png",alt:"Photorealistic 3D reconstruction of ancient astronomers observing the Milky Way",facts:[["OBJECT","Clay star catalogues"],["LEGACY","Recorded cycles"]]},
  {eyebrow:"MYTHS IN THE STARS",title:"One Sky, Many Stories",period:"Ancient Worlds",intro:"The same stars became hunters, gods, hearths and guides across different cultures.",body:"Greeks saw Orion the hunter; ancient Egyptians associated this region with Osiris; Maya traditions read Orion's belt and nebula as the hearth of creation. A constellation is both a pattern and a cultural mirror.",image:"/exhibit-orion-myth.png",alt:"Photorealistic 3D celestial sculpture of Orion formed from stars",facts:[["GREECE","Orion the hunter"],["EGYPT","Osiris"]]},
  {eyebrow:"CELESTIAL NAVIGATION",title:"The Ocean Was a Map",period:"c. 1000–1300 CE",intro:"Pacific wayfinders crossed immense distances using stars, swells, wind and wildlife.",body:"Polynesian navigators carried a living star compass in memory. By reading the rising and setting points of celestial bodies, crews connected islands across the largest ocean on Earth.",image:"/exhibit-polynesian-wayfinders.png",alt:"Photorealistic 3D Polynesian wayfinders navigating by the night sky",facts:[["INSTRUMENT","The remembered sky"],["OCEAN","Pacific"]]},
  {eyebrow:"THE SPACE AGE",title:"One Small Step",period:"20 July 1969",intro:"Apollo 11 turned the Moon from a distant light into a place humans had visited.",body:"The mission combined centuries of celestial mechanics with new computers, materials and human courage. Its view back toward Earth also changed how many people understood our shared world.",image:"/exhibit-apollo-moon.png",alt:"Photorealistic 3D reconstruction of an Apollo astronaut and lunar module",facts:[["MISSION","Apollo 11"],["CREW","3 explorers"]]},
  {eyebrow:"INTERSTELLAR MESSAGE",title:"Beyond the Sun",period:"1977—Now",intro:"Voyager carries a portrait of Earth into the space between stars.",body:"The twin probes revealed the outer planets before crossing the heliosphere. Their Golden Records preserve sounds, images and greetings as a message to an unknown future audience.",image:"/exhibit-voyager-frontier.png",alt:"Photorealistic 3D Voyager spacecraft at the edge of the heliosphere",facts:[["RECORD","Sounds of Earth"],["STATUS","Interstellar"]]},
];

export default function Page(){return <InfiniteExhibition chapter="COSMIC ARCHIVE" title="We have always looked up." lede="A horizontal exhibition tracing the stories, myths and discoveries that shaped humanity's relationship with the sky." note="Five moments that changed how we see the universe." items={items}/>}
