import SpaceDetail from "../components/SpaceDetail";
export const dynamic = "force-static";
const items=[
{eyebrow:"ORBITAL RESEARCH",title:"International Space Station",intro:"A permanently crewed laboratory circles Earth roughly sixteen times each day.",image:"/satellite-station-transparent.png",facts:[["ALTITUDE","408 km"],["CREW","7 typical"]] as Array<[string,string]>,body:"The ISS supports microgravity research, Earth observation and technology demonstrations across international partner agencies."},
{eyebrow:"SPACE OBSERVATORY",title:"Hubble Space Telescope",intro:"A 2.4-metre mirror observes the universe above most atmospheric distortion.",image:"/satellite-telescope-transparent.png",facts:[["ALTITUDE","525 km"],["LAUNCHED","1990"]] as Array<[string,string]>,body:"Hubble transformed astronomy through deep-field imaging, precise distance measurements and long-running ultraviolet observations."},
{eyebrow:"EARTH OBSERVATION",title:"Sentinel-2",intro:"Twin multispectral satellites revisit land and coastal regions every few days.",image:"/satellite-sentinel2-transparent.png",facts:[["ALTITUDE","786 km"],["BANDS","13 spectral"]] as Array<[string,string]>,body:"Sentinel-2 maps vegetation, water, wildfire damage and urban change for the European Copernicus programme."},
{eyebrow:"WEATHER WATCH",title:"GOES-19",intro:"A geostationary platform watches the same hemisphere continuously.",image:"/satellite-goes19-transparent.png",facts:[["ALTITUDE","35,786 km"],["ORBIT","Geostationary"]] as Array<[string,string]>,body:"Rapid imagery and space-weather instruments help forecasters follow severe storms, lightning and solar activity."},
{eyebrow:"NAVIGATION",title:"GPS III",intro:"Atomic clocks turn orbital timing into precise positioning across Earth.",image:"/satellite-earth-observer-transparent.png",facts:[["ALTITUDE","20,200 km"],["CLOCKS","Atomic"]] as Array<[string,string]>,body:"The constellation supports navigation, telecommunications timing, mapping, transport and scientific measurement."},
{eyebrow:"DEEP SPACE",title:"James Webb Space Telescope",intro:"A segmented infrared observatory operates around the Sun–Earth L2 point.",image:"/satellite-infrared-transparent.png",facts:[["DISTANCE","1.5M km"],["MIRROR","6.5 m"]] as Array<[string,string]>,body:"Webb studies the first galaxies, stellar nurseries and exoplanet atmospheres behind a five-layer sunshield."}
];
export default function Page(){return <SpaceDetail section="ORBITAL OPERATIONS" title="Machines above us." lede="A working layer of observation, communication and navigation around Earth." items={items}/>}
