import SpaceDetail from "../components/SpaceDetail";

export const dynamic = "force-static";

const items=[
  {eyebrow:"DWARF PLANET · ASTEROID BELT",title:"Ceres",intro:"The largest object in the asteroid belt and a world rich in water-bearing minerals.",image:"/object-asteroid-transparent.png",facts:[["DIAMETER","940 km"],["ORBIT","4.6 years"]] as Array<[string,string]>,body:"Ceres is massive enough to be rounded by its own gravity. Bright salt deposits reveal evidence of geologically recent briny activity."},
  {eyebrow:"ROCKY ASTEROID",title:"Vesta",intro:"A differentiated protoplanet preserving an ancient volcanic surface.",image:"/object-asteroid-transparent.png",facts:[["DIAMETER","525 km"],["ORBIT","3.6 years"]] as Array<[string,string]>,body:"A vast impact basin dominates Vesta's southern hemisphere, and fragments blasted away from it have reached Earth as meteorites."},
  {eyebrow:"NEAR-EARTH ASTEROID",title:"Bennu",intro:"A carbon-rich rubble pile assembled from fragments of a larger parent body.",image:"/object-asteroid-transparent.png",facts:[["DIAMETER","492 m"],["DAY","4.3 hours"]] as Array<[string,string]>,body:"Bennu's loose surface records primitive Solar System chemistry and was sampled directly by the OSIRIS-REx mission."},
  {eyebrow:"BARRED SPIRAL GALAXY",title:"The Milky Way",intro:"Our home galaxy, viewed from within one of its minor spiral arms.",image:"/object-galaxy-transparent.png",facts:[["DIAMETER","100K light-years"],["STARS","100–400B"]] as Array<[string,string]>,body:"The Solar System circles the galactic centre roughly once every 230 million years, about halfway out from the core."},
  {eyebrow:"SPIRAL GALAXY",title:"Andromeda",intro:"The nearest major galactic neighbour to the Milky Way.",image:"/object-galaxy-transparent.png",facts:[["DISTANCE","2.5M light-years"],["CATALOGUE","M31"]] as Array<[string,string]>,body:"Andromeda is approaching the Milky Way. Over immense timescales, their mutual gravity will reshape both galaxies."},
  {eyebrow:"UNBARRED SPIRAL GALAXY",title:"Sombrero Galaxy",intro:"A luminous central bulge crossed by a dramatic lane of dark dust.",image:"/object-galaxy-transparent.png",facts:[["DISTANCE","29M light-years"],["CATALOGUE","M104"]] as Array<[string,string]>,body:"Seen nearly edge-on, the Sombrero Galaxy combines a bright stellar halo with a sharply defined ring of dust and gas."},
  {eyebrow:"CELESTIAL MAP",title:"Orion",intro:"A familiar stellar pattern visible from both hemispheres.",image:"/object-constellation-transparent.png",facts:[["BRIGHTEST","Rigel"],["NEBULA","M42"]] as Array<[string,string]>,body:"Orion's stars appear close on the sky but sit at very different distances, forming a line of sight rather than a physical group."},
  {eyebrow:"NORTHERN CONSTELLATION",title:"Ursa Major",intro:"A broad northern constellation containing the Big Dipper asterism.",image:"/object-constellation-transparent.png",facts:[["BRIGHTEST","Alioth"],["AREA","1,280 sq. deg."]] as Array<[string,string]>,body:"Two stars in the Big Dipper point toward Polaris, making Ursa Major a practical landmark for northern sky navigation."},
  {eyebrow:"NORTHERN CONSTELLATION",title:"Cassiopeia",intro:"A distinctive W-shaped pattern circling the northern celestial pole.",image:"/object-constellation-transparent.png",facts:[["BRIGHTEST","Schedar"],["SHAPE","Five-star W"]] as Array<[string,string]>,body:"Cassiopeia lies against the rich star fields of the Milky Way and contains clusters, nebulae and remnants of exploded stars."},
  {eyebrow:"PROPOSED ORBITAL COMPUTE",title:"SpaceX Orbital Data Center",intro:"A proposed non-geostationary satellite network designed to place high-density computing infrastructure in orbit.",image:"/spacex-orbital-data-center-transparent.png",facts:[["STATUS","FCC filing"],["ALTITUDE","500–2,000 km"]] as Array<[string,string]>,body:"SpaceX filed its Orbital Data Center system application in January 2026. The proposal describes solar-powered compute satellites connected through high-bandwidth optical links; it is a proposed system, not an operational space data center."},
];

export default function Page(){return <SpaceDetail section="DEEP SPACE ARCHIVE" title="Beyond our system." lede="Explore asteroids, galaxies, constellations and emerging orbital infrastructure across distances that resist ordinary scale." items={items}/>}
