import InfiniteExhibition, { type ExhibitionItem } from "../components/InfiniteExhibition";

export const dynamic = "force-static";

const items: ExhibitionItem[] = [
  {eyebrow:"THE ATMOSPHERIC EDGE",title:"Our Thin Blue Shelter",period:"0—100 km",intro:"Almost everything that protects and sustains us is held in a remarkably thin layer.",body:"The atmosphere filters radiation, moderates temperature and carries weather. From orbit, it appears as a narrow blue line hugging the curve of Earth.",image:"/near-earth-atmosphere.png",alt:"Photorealistic 3D view of Earth's thin atmospheric layers at sunrise",facts:[["KÁRMÁN LINE","100 km"],["AURORA","80–500 km"]]},
  {eyebrow:"LOW EARTH ORBIT",title:"The Busy First Frontier",period:"160—2,000 km",intro:"Astronauts, observatories and Earth-imaging satellites move through this crowded region.",body:"The International Space Station circles Earth roughly every 90 minutes. Nearby spacecraft monitor crops, oceans, weather, fires and the changing climate.",image:"/near-earth-leo.png",alt:"Photorealistic 3D International Space Station and satellites above Earth",facts:[["ISS ALTITUDE","~400 km"],["ORBIT","~90 min"]]},
  {eyebrow:"MAGNETIC SHIELD",title:"Weather from the Sun",period:"Sun—Earth System",intro:"An invisible magnetic shield redirects much of the charged solar wind around Earth.",body:"When solar activity disturbs this shield, geomagnetic storms can brighten auroras—and disrupt satellites, radio links, navigation and power networks.",image:"/near-earth-magnetosphere.png",alt:"Photorealistic 3D scientific visualization of Earth's magnetosphere and solar wind",facts:[["BOW SHOCK","~90,000 km"],["SIGNAL","Aurora"]]},
  {eyebrow:"GLOBAL INFRASTRUCTURE",title:"Orbits That Run the World",period:"2,000—35,786 km",intro:"Navigation, weather forecasting and communication rely on carefully chosen orbital paths.",body:"GPS constellations occupy medium Earth orbit, while geostationary spacecraft match Earth's rotation and appear fixed above one longitude.",image:"/near-earth-orbits.png",alt:"Photorealistic 3D satellite orbit architecture around Earth",facts:[["GPS","MEO"],["GEO","35,786 km"]]},
  {eyebrow:"CISLUNAR SPACE",title:"The Next Neighborhood",period:"384,400 km",intro:"Between Earth and Moon lies a dynamic landscape shaped by the gravity of both worlds.",body:"Future crews, gateways and robotic missions will use cislunar trajectories and stable gravitational regions as stepping stones for sustained lunar exploration.",image:"/near-earth-cislunar.png",alt:"Photorealistic 3D Earth-Moon cislunar space with spacecraft",facts:[["MOON","384,400 km"],["JOURNEY","~3 days"]]},
];

export default function Page(){return <InfiniteExhibition chapter="NEAR-EARTH SPACE" title="Your cosmic neighborhood." lede="Travel outward from the atmosphere to the Moon and discover the invisible systems surrounding our planet." note="Five layers between home and the lunar frontier." items={items} tone="orbit"/>}
